VAGRANTFILE_API_VERSION = "2"
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "hashicorp/precise32"
  config.vm.hostname = "draleche"
  config.vm.provision :shell, :path => "vagrant/provision.sh"
  config.vm.network :private_network, ip: "192.168.50.4"
 
end